In [8]:
import tensorflow as tf

In [9]:
print(tf.__version__)

2.7.0


### Why are tensors important?

Initializing tensors

In [10]:
t = tf.constant(2)
print(t)

tf.Tensor(2, shape=(), dtype=int32)


In [11]:
t = tf.constant([[1, 2],
                [3, 4]])
print(t)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [12]:
tf.ones((3, 3))
# there is also zeros, eye(for identity matrix) and normal(random according to the normal distribution)
#print(t)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

Mathematical operations

In [13]:
x = tf.constant([1, 1, 1])
y = tf.constant([2, 3, 4])

Addition

In [14]:
z = tf.add(x, y)
print(z)
z = x + y
print(z)

tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)


Subtraction

In [15]:
z = tf.subtract(x, y)
print(z)
z = x - y
print(z)

tf.Tensor([-1 -2 -3], shape=(3,), dtype=int32)
tf.Tensor([-1 -2 -3], shape=(3,), dtype=int32)


Division

In [16]:
z = tf.divide(x, y)
print(z)
z = x / y
print(z)

tf.Tensor([0.5        0.33333333 0.25      ], shape=(3,), dtype=float64)
tf.Tensor([0.5        0.33333333 0.25      ], shape=(3,), dtype=float64)


Multiplication (elementwise)

In [17]:
z = tf.multiply(x, y)
print(z)
z = x * y
print(z)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


Matrix multiplication

In [8]:
x = tf.constant([[1, 2],
                [3, 4]], dtype = 'float32')
y = tf.eye(2)

print(x)
print(y)

z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


Indexing a tensor

In [30]:
x = tf.constant([0, 1, 2, 3, 4])
print(x[0])
print(x[0:2])
print(x[:])

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [33]:
x = tf.constant([[1, 2],
                [3, 4]])

print(x[0, :])
print(x[:, 0])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)


Tensor reshaping

In [36]:
x = tf.constant([0, 1, 2, 3, 4, 5])
x = tf.reshape(x, (3, 2))
print(x)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)


In [39]:
x = tf.reshape(x, (3, -1))
print(x)
x = tf.reshape(x, (-1, 2))
print(x)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int32)
